window.followConfig = {
  bigTotal: 350000,
  myTotal: 3500,
  rows: [
    {
      name: "嘉实上证科创板芯片 ETF 联接 C",
      amount: 62922,
      currentInvest: 0,
      color: "",
      toFill: 629.22,
    },
    {
      name: "永赢先进制造智选混合 C",
      amount: 63448,
      currentInvest: 0,
      color: "",
      toFill: 634.48,
    },
    {
      name: "德邦半导体产业混合 C",
      amount: 19440,
      currentInvest: 0,
      color: "",
      toFill: 194.4,
    },
    {
      name: "华夏恒生科技 ETF 联接（QDII）C",
      amount: 89870,
      currentInvest: 0,
      color: "",
      toFill: 898.7,
    },
    {
      name: "博时中证机器人指数 C",
      amount: 25169,
      currentInvest: 0,
      color: "",
      toFill: 251.69,
    },
    {
      name: "天弘创业板 ETF 联接 C",
      amount: 18821,
      currentInvest: 0,
      color: "",
      toFill: 188.21,
    },
    {
      name: "易方达科创 50 联接 C",
      amount: 19769,
      currentInvest: 0,
      color: "",
      toFill: 197.69,
    },
    {
      name: "德邦稳盈增长灵活配置混合 C",
      amount: 3000,
      currentInvest: 30,
      color: "",
      toFill: 20,
    },
    {
      name: "永赢信息产业智选混合 C",
      amount: 2000,
      currentInvest: 2000,
      color: "#ef4444",
      toFill: -1980,
    },
    {
      name: "北信瑞丰产业升级多策略混合型",
      amount: 9000,
      currentInvest: 0,
      color: "",
      toFill: 90,
    },
  ],
  version: 3,
};
