CREATE DATABASE IF NOT EXISTS student
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE student;

CREATE TABLE IF NOT EXISTS user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(128) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'user',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stu_info (
  id BIGINT NOT NULL AUTO_INCREMENT,
  stu_no VARCHAR(64) NOT NULL,
  stu_name VARCHAR(64) NOT NULL,
  gender VARCHAR(16) NOT NULL,
  age INT NOT NULL,
  class_name VARCHAR(128) NOT NULL,
  height DOUBLE NOT NULL,
  weight DOUBLE NOT NULL,
  score DOUBLE NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_stu_info_stu_no (stu_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stu_test_record (
  id BIGINT NOT NULL AUTO_INCREMENT,
  stu_no VARCHAR(64) NOT NULL,
  term VARCHAR(64) NOT NULL,
  height DOUBLE DEFAULT NULL,
  weight DOUBLE DEFAULT NULL,
  bmi DOUBLE DEFAULT NULL,
  score_total DOUBLE DEFAULT NULL,
  warning_tag VARCHAR(128) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_record_stu_term (stu_no, term)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO user (username, password, role)
VALUES ('admin', 'admin123', 'admin')
ON DUPLICATE KEY UPDATE role = VALUES(role);
